### ISSUE TITLE
bug: display table schema error

### ISSUE THREAD

**Issue by BowenXiao1999** [risingwavelabs/sqlalchemy-risingwave#13]
<img width="407" alt="image" src="https://user-images.githubusercontent.com/36908971/201261094-707d01b2-b419-43be-9f38-9598a5b1cce9.png"> There is also error log in bottom right.

It is expected to show table schema.

```
Traceback (most recent call last):
  File "/usr/local/lib/python3.8/site-packages/flask_appbuilder/api/__init__.py", line 86, in wraps
    return f(self, *args, **kwargs)
  File "/app/superset/views/base_api.py", line 114, in wraps
    raise ex
  File "/app/superset/views/base_api.py", line 111, in wraps
    duration, response = time_function(f, self, *args, **kwargs)
  File "/app/superset/utils/core.py", line 1574, in time_function
    response = func(*args, **kwargs)
  File "/app/superset/utils/log.py", line 244, in wrapper
    value = f(*args, **kwargs)
  File "/app/superset/databases/api.py", line 536, in table_metadata
    table_info = get_table_metadata(database, table_name, schema_name)
  File "/app/superset/databases/utils.py", line 75, in get_table_metadata
    keys += foreign_keys + indexes
TypeError: can only concatenate list (not "dict") to list

```

**Comment by BowenXiao1999** [comment]
Verified. This should solved by 696ef.
